# Generated by Django 4.0 on 2021-12-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogchat_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='logo_uploaded')),
                ('logo_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
