# Generated by Django 4.0 on 2021-12-11 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogchat_app', '0003_navbarmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbarmodel',
            name='navbar_logo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
