# Generated by Django 4.0 on 2021-12-11 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogchat_app', '0004_navbarmodel_navbar_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headimage', models.ImageField(blank=True, null=True, upload_to='aboutimage_uploaded')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('text', models.CharField(blank=True, max_length=400, null=True)),
                ('ownimage', models.ImageField(blank=True, null=True, upload_to='aboutimage_uploaded')),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('profession', models.CharField(blank=True, max_length=40, null=True)),
                ('small_inf', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
