# Generated by Django 4.0 on 2021-12-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogchat_app', '0005_aboutmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='pp',
            field=models.ImageField(blank=True, null=True, upload_to='images_uploaded'),
        ),
    ]
