# Generated by Django 4.0 on 2021-12-14 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogchat_app', '0007_remove_postmodel_pp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adreess', models.CharField(blank=True, max_length=100, null=True)),
                ('adreessurl', models.URLField(blank=True, max_length=100, null=True)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('short_imf', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
