# Generated by Django 4.0 on 2021-12-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogchat_app', '0008_contactmodel2'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=1000)),
            ],
        ),
    ]
