# Generated by Django 4.0 on 2021-12-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogchat_app', '0013_remove_postmodel_category_postmodel_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='semester',
        ),
        migrations.AddField(
            model_name='postmodel',
            name='category',
            field=models.CharField(blank=True, choices=[('Personal Post', 'Personal Post'), ('Visual Designs', 'Visual Designs'), ('Travel Events', 'Travel Events'), ('Web Development', 'Web Development'), ('Video and Audio', 'Video and Audio')], default='Personal Post', max_length=20, null=True),
        ),
    ]
