# Generated by Django 4.0 on 2021-12-21 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogchat_app', '0015_categorymodel_alter_postmodel_category'),
        ('blogchat_app', '0015_categorymodel_remove_postmodel_category_and_more'),
    ]

    operations = [
    ]
