# Generated by Django 4.0 on 2021-12-21 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogchat_app', '0016_merge_20211221_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='category',
        ),
    ]
