# Generated by Django 4.0 on 2022-01-01 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogchat_app', '0019_message_room'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
