# Generated by Django 4.0 on 2022-01-07 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogchat_app', '0021_message_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='image',
            field=models.ImageField(blank=True, default='images_uploaded/925667.jpg', null=True, upload_to='images_uploaded'),
        ),
    ]
